name: Add milestone to issue

on:
  issues:
    types: 
      - opened
      - reopened

jobs:
  add-milestone-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Parsing issue
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/challenge.yml
      - name: Adding milestone to issue
        uses: Julexar/Milestone-Assigner@v1.0
        with:
          token: "${{ secrets.ACTION_TOKEN }}"
          milestone: "${{ steps.issue-parser.outputs.issueparser_challenge-year }} Challenges"
